# For mimic joint plugin
gazebo_ros_control:
  pid_gains:
    left_l_finger_tip_joint:
      p: 50.0
      i: 1.0
      d: 0.0
      i_clamp: 100
      antiwindup: true
      publish_state: false
    right_l_finger_tip_joint:
      p: 50.0
      i: 1.0
      d: 0.0
      i_clamp: 100
      antiwindup: true
      publish_state: false

    left_r_finger_tip_joint:
      p: 50.0
      i: 1.0
      d: 0.0
      i_clamp: 100
      antiwindup: true
      publish_state: false
    right_r_finger_tip_joint:
      p: 50.0
      i: 1.0
      d: 0.0
      i_clamp: 100
      antiwindup: true
      publish_state: false
